inherit_from: .rubocop_todo.yml
inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5.0
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'script/**/*'
    - 'bundle_bin/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'Guardfile'
    - 'Rakefile'
    - 'lib/tasks/**'

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# "Style/ClassAndModuleChildren: Use nested module/class definitions instead of compact style."をParentClass::ChildClass形式にする
ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'app/channels/application_cable/connection.rb'
    - 'app/channels/application_cable/channel.rb'
    - 'config/application.rb'

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false

# "Style/WordArray: Use `%w` or `%W` for an array of words."を無効
Style/WordArray:
  Enabled: false

# Style/SymbolArray: Use `%i` or `%I` for an array of symbols.
Style/SymbolArray:
  Enabled: false

# 文字列にはシングルクオートを使う
Style/StringLiterals:
  EnforcedStyle: single_quotes
