version: '2'
services:
  db:
    image: postgres:10.1
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=VHgpFjfP2G"

  web:
    build: .
    command: ./scripts/start.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/var/www/app
    working_dir: /var/www/app
    links:
      - db
    stdin_open: true
    tty: true
