# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:10.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: VHgpFjfP2G
      - image: redis:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        
      # Database setup
      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create db:schema:load
          environment:
            DATABASE_URL: "postgres://postgres@localhost:5432/db"

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            
            bundle exec rspec --format progress \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES
          environment:
            DATABASE_URL: "postgres://postgres@localhost:5432/db"

      # Check Rubocop
      - run:
          name: RuboCop Style Check
          command: bundle exec rubocop

      # collect reports
      - store_test_results:
          path: /test-results
