default: &default
  adapter: postgresql
  encoding: utf8
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  database: ort_database
  password: VHgpFjfP2G
  timeout: 10000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  encoding: unicode
  pool: 5
